### ISSUE TITLE
Lenovo ThinkPad P50 works

### ISSUE THREAD

**Issue by jkuroda** [ayeks/SGX-hardware#7]
Confirmed: Lenovo ThinkPad P50 laptops have BIOS support for SGX with SGX-enabled CPUs.
- ![P50 BIOS Screen 1](https://cloud.githubusercontent.com/assets/1642059/15412600/bea573b8-1ddd-11e6-917e-5d0a45eac0e3.JPG)
- ![P50 BIOS Screen 2](https://cloud.githubusercontent.com/assets/1642059/15412603/c3c63f4e-1ddd-11e6-8325-aba557e9f1e8.JPG)
- ![P50 - Ubuntu 16.04 LTS with Intel isgx driver](https://cloud.githubusercontent.com/assets/1642059/15412605/c8baa36e-1ddd-11e6-9c5f-0c83053e398b.JPG)

Likely: Lenovo ThinkPad P70, P50S, T560, T460p, T460s, T460 laptops as well based on user manuals:
- https://download.lenovo.com/pccbbs/mobiles_pdf/p70_ug_en.pdf#page=95
- https://download.lenovo.com/pccbbs/mobiles_pdf/p50_ug_en.pdf#page=96
- https://download.lenovo.com/pccbbs/mobiles_pdf/t560_p50s_ug_en.pdf#page=100
- https://download.lenovo.com/pccbbs/mobiles_pdf/t460_ug_en.pdf#page=103
- https://download.lenovo.com/pccbbs/mobiles_pdf/t460p_ug_en.pdf#page=95
- https://download.lenovo.com/pccbbs/mobiles_pdf/t460s_ug_en.pdf#page=92

**Comment by bl4ck5un** [comment]
Confirmed T460s

**Comment by ayeks** [comment]
Thanks for your contribution and the screenshots!

Does someone know how SGX can be activated via software? In my understanding it is not possible to modify the MSR.IA32_Feature_Control.SGX_Enable bit once the MSR lock bit is set. That happens when the BIOS boots the system. Does someone has more information about that or can paste the output of the [test-sgx.c](https://github.com/ayeks/SGX-hardware/blob/master/test-sgx.c) tool with activated sofware controlled SGX?

**Comment by jkuroda** [comment]
[test-sgx-enabled.txt](https://github.com/ayeks/SGX-hardware/files/287636/test-sgx-enabled.txt)
[test-sgx-sw_controlled.txt](https://github.com/ayeks/SGX-hardware/files/287637/test-sgx-sw_controlled.txt)

With "Software Controlled", the driver loads, but it also reports that "CPU does not support the SGX 1.0 instruction set".
With "Enabled", the driver loads and reports the expected EPC messages.

Have not had a chance to explore further.
