### ISSUE TITLE
Which free python version can use SGX 1 and SGX2 and how to use?

### ISSUE THREAD

**Issue by hoyeunglee** [ayeks/SGX-hardware#93]
Which free python version can use SGX 1 and SGX 2 and how to use? Is there special code to enable before programming in interactive mode in cmd of window ?

If no python use yet, which programming language can use SGX 1 and SGX 2 ?

What is the difference between enable SGX in BIOS manually and using Intel Activation app in Microsoft store ?

Microsoft office Excel have formula and word file etc, how to know which version of office can use SGX 2 or SGX 1?

Search result show vulnerability SmashEX related with SGX. How to prevent or mitigate?

I find baby canyon can also have SGX , which version of SGX are they ? There are optane memory and Traditional memory in baby canyon, how to know which memory and choose optane memory to run SGX. Is there needed clear optane memory after usage?

**Comment by ayeks** [comment]
Hey @hoyeunglee,

thanks for all these questions. Because this project only documents hardware that can be used for SGX and is not a developer support project, I recommend that you just checkout the official documentation: https://www.intel.com/content/www/us/en/developer/library.html?s=Newest&f:@stm_10309_en=%5BIntel%C2%AE%20Software%20Guard%20Extensions%20(Intel%C2%AE%20SGX)%5D

As you see in [test-sgx.c](https://github.com/ayeks/SGX-hardware/blob/master/test-sgx.c) I used C as programming language for my SGX projects. I have no idea if there is a python SGX lib around. :)

Cheers
Lars
